### ISSUE TITLE
Suggested changes to ReadMe

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/local-hadron-collider#2]
The `Clone the casl-ansible repository` section should say `git clone https://github.com/redhat-cop/casl-ansible`.

Perhaps add installation reference links for ansible and dnsmasq.

**Comment by donovanmuller** [comment]
The Ansible install link is provided:

<img width="950" alt="screen shot 2018-02-13 at 10 49 11" src="https://user-images.githubusercontent.com/1175891/36140909-9ffa19f6-10ab-11e8-9b37-1e6e61987ef7.png">

See the box: `... Please follow the installation guide to install for your platform.`

**Comment by donovanmuller** [comment]
@kbristow the problem with installing dnsmasq is that there is no one page that describes how to install for the various platforms.

I will add a mention on how to install for macOS?

**Comment by kbristow** [comment]
I was thinking a link to the website but I see that is mostly useless too. Since that is not the only way to do it (host file solution is there too) maybe it is acceptable? Seems wrong just putting a mac installation guide.

**Comment by donovanmuller** [comment]
Agreed. Let's keep macOS example for now and expand as needed. For example, it might be interesting when @KieranHons tries this out :smile:
